### PR TITLE
Added a POST method that returns only a string.

### PR DESCRIPTION
**Pull request by GustavoArriola**
Added a POST method that returns only a string. It's usefull when you are using a service like 'SBOBobService_GetSystemCurrency'. This service just returns a string, while the default PostStringAsync  (<data>) make a json convertion that returns an exception.

### CODE REVIEW

**Comment by bgmulinari** [comment]
Hi, @GustavoArriola. Thanks for your PR.

I think this is a good addition as this is a scenario I hadn't considered. However, the only issue I have with your commit is the name of the method, because unlike the other `PostStringAsync` overloads, in your case you are not actually posting a string, but rather receiving one. With that said, I think a more suitable name for it would be `PostReceiveStringAsync`.

**Comment by GustavoArriola** [comment]
Thanks @bgmulinari for your comment! I made the change. Regards!

**Comment by bgmulinari** [comment]
@GustavoArriola, I will be merging this PR into the dev branch, so this change should be made available in the next B1SLayer release.

Thanks for your contribution! 👍

**Comment by bgmulinari** [comment]
This change is now available in version [1.3.0](https://github.com/bgmulinari/B1SLayer/releases/tag/1.3.0).

**Pull request merged**
